#!/bin/bash

NORMAL='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
BLINK='\033[5m'

WHITE='\033[0;97m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'

usage="${WHITE}Usage: $0 [--cflags] [--libs]"

cpp_standard="c++20"
bin_name="main"

if [ "$#" -lt 1 ]; then
    >&2 echo -e "${RED}${BOLD}Error: Too few arguments passed"
    >&2 echo -e ${usage}
    exit 1
fi

while test $# -gt 0; do
  case $1 in
    --cflags)
      echo -std=${cpp_standard} -o ${bin_name} -I./include -Wall -Wextra -Wpedantic \
	  ./src/main.cpp \
\
	  ./src/Game/Configuration.cpp \
	  ./src/Game/EventHandler.cpp \
	  ./src/Game/Game.cpp \
	  ./src/Game/objectStorage.cpp \
\
	  ./src/Sound/channelControl.cpp \
	  ./src/Sound/soundChunk.cpp \
	  ./src/Sound/soundMusic.cpp \
	  ./src/Sound/volumeControl.cpp \
\
	  ./src/Sprite/AnimatedSprite.cpp \
	  ./src/Sprite/Asteroid.cpp \
	  ./src/Sprite/Gem.cpp \
	  ./src/Sprite/IMGSprite.cpp \
	  ./src/Sprite/Player.cpp \
	  ./src/Sprite/Sprite.cpp \
	  ./src/Sprite/Text.cpp \
\
	  ./src/Time/Time.cpp
      ;;

    --libs)
      echo \
	  -lSDL2main \
	  -lSDL2_image \
	  -lSDL2_mixer \
	  -lSDL2_ttf \
	  -ljxl
      ;;
  esac
  shift
done

exit 1
