#ifndef EVENT_TYPE_HPP
#define EVENT_TYPE_HPP

#include <SDL2/SDL.h>

enum EventType
{
	USEREVENT_TIMER = SDL_USEREVENT,
	NUM_EVENTS = USEREVENT_TIMER - (SDL_USEREVENT - 1)
};

#endif //! EVENT_TYPE_HPP