#ifndef EVENT_TYPE_HPP
#define EVENT_TYPE_HPP

#include <SDL2/SDL.h>

typedef enum
{
	USEREVENT_TIMER = SDL_USEREVENT,
	NUM_EVENTS = USEREVENT_TIMER - (SDL_USEREVENT - 1)
} EventType;

#endif //! EVENT_TYPE_HPP