#ifndef ANIMATION_DATA_HPP
#define ANIMATION_DATA_HPP

struct AnimationData
{
	unsigned int
		FRAME_WIDTH,
		FRAME_HEIGHT,
		IMG_FRAMES,
		IMG_TYPES,
		ANIMATIONS_PER_SECOND;
};

#endif //! ANIMATION_DATA_HPP